version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: kpadb-mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/dawid/Desktop/UWR/KPAZBD/lista06/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped